// GENERATED by scripts/port-demo-mockdata.mjs — 勿手改;源:docs/demo/js/data.js @ 06ff9ba
// mock 数据单一事实来源;组件禁止直接 import,须经 data/ 接缝(src/renderer/src/data/index.ts)

import type {
  Agent,
  AgentForm,
  AppUrls,
  DrawerStatusModel,
  InvalidPlist,
  LogLine,
  OpsState
} from '@shared/models'

export interface MockData {
  urls: AppUrls
  agents: Agent[]
  invalidPlists: InvalidPlist[]
  aiAgents: { id: string; name: string; cli: string; version: string; path: string | null; status: 'installed' | 'not_found'; descKey: string; tags: string[]; icon: string }[]
  aiSkills: { id: string; nameKey: string; descKey: string; tag: string; icon: string }[]
  liveLogs: [LogLine['type'], string][]
  drawer: {
    title: string
    scope: string
    opsState: OpsState
    form: AgentForm
    status: DrawerStatusModel
    logLines: [string, LogLine['type'], string][]
    xml: string
  }
}

export const MOCK_DATA: MockData = {
  "urls": {
    "github": "https://github.com/BeCrafter/Launcher",
    "help": "https://github.com/BeCrafter/Launcher/blob/main/Help.md"
  },
  "agents": [
    {
      "id": "com.user.sync-daemon",
      "label": "com.user.sync-daemon",
      "desc": "实时监听文件变更并自动同步至远端存储，支持增量传输与冲突检测。",
      "status": "running",
      "pid": 2847,
      "uptime": "3h 24m",
      "scope": "user",
      "tags": [
        "sync",
        "daemon"
      ],
      "program": "/usr/local/bin/sync-daemon",
      "exitCode": 0,
      "restarts": 2
    },
    {
      "id": "homebrew.mxcl.nginx",
      "label": "homebrew.mxcl.nginx",
      "desc": "Nginx HTTP 服务器，由 Homebrew Services 管理。",
      "status": "running",
      "pid": 3201,
      "uptime": "5h 12m",
      "scope": "user",
      "tags": [
        "brew",
        "server"
      ],
      "isBrew": true,
      "program": "/usr/local/opt/nginx/bin/nginx",
      "exitCode": 0,
      "restarts": 0
    },
    {
      "id": "com.user.backup-cron",
      "label": "com.user.backup-cron",
      "desc": "每日凌晨执行全量备份，自动压缩并上传至对象存储，保留最近 30 份记录。",
      "status": "running",
      "pid": 3102,
      "uptime": "1h 05m",
      "scope": "user",
      "tags": [
        "backup",
        "cron"
      ],
      "program": "/usr/local/bin/backup.sh",
      "exitCode": 0,
      "restarts": 1
    },
    {
      "id": "com.corp.log-cleaner",
      "label": "com.corp.log-cleaner",
      "desc": "定期扫描并删除超过 7 天的过期日志文件，释放磁盘空间。",
      "status": "loaded",
      "pid": null,
      "uptime": null,
      "scope": "system",
      "tags": [
        "log",
        "cleanup"
      ],
      "program": "/usr/local/bin/log-cleaner",
      "exitCode": null,
      "restarts": 0
    },
    {
      "id": "com.user.notify-push",
      "label": "com.user.notify-push",
      "desc": "监听系统事件并通过 APNs 发送本地推送通知，当前已停止运行。",
      "status": "stopped",
      "pid": null,
      "uptime": null,
      "scope": "user",
      "tags": [
        "notify"
      ],
      "program": "/usr/local/bin/notify-push",
      "exitCode": 1,
      "restarts": 3
    },
    {
      "id": "com.system.net-watchdog",
      "label": "com.system.net-watchdog",
      "desc": "守护网络连通性，断网时执行回调并发送告警，系统 Daemon 级别运行。",
      "status": "stopped",
      "pid": null,
      "uptime": null,
      "scope": "daemon",
      "tags": [
        "network",
        "daemon"
      ],
      "program": "/usr/sbin/net-watchdog",
      "exitCode": 0,
      "restarts": 0
    }
  ],
  "invalidPlists": [
    {
      "path": "~/Library/LaunchAgents/com.old.broken.plist",
      "reason": "XML 解析失败：预期 </dict> 但遇到 EOF"
    }
  ],
  "aiAgents": [
    {
      "id": "claude",
      "name": "Claude",
      "cli": "claude",
      "version": "2.1.0",
      "path": "/usr/local/bin/claude",
      "status": "installed",
      "descKey": "ai.agent.claude.desc",
      "tags": [
        "anthropic",
        "coding"
      ],
      "icon": "fa-solid fa-clone"
    },
    {
      "id": "codex",
      "name": "Codex",
      "cli": "codex",
      "version": "0.4.0",
      "path": "/usr/local/bin/codex",
      "status": "installed",
      "descKey": "ai.agent.codex.desc",
      "tags": [
        "openai",
        "coding"
      ],
      "icon": "fa-solid fa-code"
    },
    {
      "id": "aider",
      "name": "Aider",
      "cli": "aider",
      "version": "0.62.0",
      "path": "/opt/homebrew/bin/aider",
      "status": "installed",
      "descKey": "ai.agent.aider.desc",
      "tags": [
        "openai",
        "git"
      ],
      "icon": "fa-solid fa-code-branch"
    },
    {
      "id": "gemini",
      "name": "Gemini CLI",
      "cli": "gemini",
      "version": "—",
      "path": null,
      "status": "not_found",
      "descKey": "ai.agent.gemini.desc",
      "tags": [
        "google"
      ],
      "icon": "fa-solid fa-wand-magic-sparkles"
    }
  ],
  "aiSkills": [
    {
      "id": "sk-plist",
      "nameKey": "ai.skill.plist.name",
      "descKey": "ai.skill.plist.desc",
      "tag": "plist",
      "icon": "fa-file-circle-plus"
    },
    {
      "id": "sk-diag",
      "nameKey": "ai.skill.diag.name",
      "descKey": "ai.skill.diag.desc",
      "tag": "diagnose",
      "icon": "fa-stethoscope"
    },
    {
      "id": "sk-refactor",
      "nameKey": "ai.skill.refactor.name",
      "descKey": "ai.skill.refactor.desc",
      "tag": "refactor",
      "icon": "fa-wand-magic-sparkles"
    },
    {
      "id": "sk-import",
      "nameKey": "ai.skill.import.name",
      "descKey": "ai.skill.import.desc",
      "tag": "import",
      "icon": "fa-file-import"
    }
  ],
  "liveLogs": [
    [
      "info",
      "[INFO] Heartbeat ping sent."
    ],
    [
      "ok",
      "[OK] Remote responded in 38ms."
    ],
    [
      "",
      "Watching for file changes…"
    ],
    [
      "warn",
      "[WARN] Rate limit approaching (87/100)."
    ],
    [
      "ok",
      "[OK] Sync complete: notes.txt"
    ],
    [
      "info",
      "[INFO] Memory: 18.4 MB · CPU: 1.2%"
    ]
  ],
  "drawer": {
    "title": "com.user.sync-daemon",
    "scope": "用户级 · ~/Library/LaunchAgents",
    "opsState": {
      "loaded": true,
      "enabled": true,
      "running": true
    },
    "form": {
      "label": "com.user.sync-daemon",
      "desc": "实时监听文件变更并自动同步至远端存储，支持增量传输与冲突检测。",
      "processType": "Background",
      "program": "/usr/local/bin/sync-daemon",
      "args": [
        "--config",
        "/Users/user/.sync/config.json",
        "--verbose"
      ],
      "workingDir": "/Users/user/Documents",
      "nice": 0,
      "throttleInterval": 10,
      "env": {
        "SYNC_TOKEN": "sk-xxxxxx"
      },
      "triggers": {
        "runAtLoad": true,
        "keepAlive": true,
        "watchPaths": false,
        "startCalendarInterval": false,
        "startInterval": 300
      },
      "keepAliveMode": "dict",
      "keepAliveDict": {
        "crashed": true,
        "afterInitialDemand": false,
        "successfulExit": false
      },
      "watchPaths": [
        "/Users/user/Documents"
      ],
      "sciEntries": [
        {
          "Minute": 0,
          "Hour": 10
        }
      ],
      "stdout": "/tmp/sync-daemon.out",
      "stderr": "/tmp/sync-daemon.err"
    },
    "status": {
      "state": "running",
      "pid": 2847,
      "uptime": "3h 24m",
      "cpu": "1.2%",
      "cpuWidth": "1.2%",
      "mem": "18.4 MB",
      "memWidth": "22%",
      "exitCode": 0,
      "restarts": 2,
      "startTime": "14:32:01",
      "plistPath": "~/Library/LaunchAgents/com.user.sync-daemon.plist",
      "workDir": "/Users/user/Documents",
      "scope": "userAgent"
    },
    "logLines": [
      [
        "14:32:01",
        "info",
        "[INFO] Service started. PID=2847"
      ],
      [
        "14:32:02",
        "",
        "Loading config from /Users/user/.sync/config.json"
      ],
      [
        "14:32:03",
        "ok",
        "[OK] Connected to remote: s3://bucket-prod"
      ],
      [
        "14:35:18",
        "",
        "Detected 3 file changes, queuing sync…"
      ],
      [
        "14:35:19",
        "ok",
        "[OK] Synced: report.pdf (2.3 MB)"
      ],
      [
        "14:38:44",
        "warn",
        "[WARN] Retry #1 - network timeout for archive.zip"
      ],
      [
        "14:38:52",
        "ok",
        "[OK] Synced: archive.zip (18.7 MB)"
      ],
      [
        "17:56:25",
        "",
        "Heartbeat check passed. Uptime=3h24m"
      ]
    ],
    "xml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\"\n  \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n  <key>Label</key>\n  <string>com.user.sync-daemon</string>\n  <key>ProgramArguments</key>\n  <array>\n    <string>/usr/local/bin/sync-daemon</string>\n    <string>--config</string>\n    <string>/Users/user/.sync/config.json</string>\n    <string>--verbose</string>\n  </array>\n  <key>WorkingDirectory</key>\n  <string>/Users/user/Documents</string>\n  <key>RunAtLoad</key>\n  <true/>\n  <key>KeepAlive</key>\n  <dict>\n    <key>Crashed</key>\n    <true/>\n  </dict>\n  <key>ProcessType</key>\n  <string>Background</string>\n  <key>ThrottleInterval</key>\n  <integer>10</integer>\n  <key>StandardOutPath</key>\n  <string>/tmp/sync-daemon.out</string>\n  <key>StandardErrorPath</key>\n  <string>/tmp/sync-daemon.err</string>\n  <key>EnvironmentVariables</key>\n  <dict>\n    <key>SYNC_TOKEN</key>\n    <string>sk-xxxxxx</string>\n  </dict>\n</dict>\n</plist>"
  }
}

// demo data.js 末尾的 URL 别名(原样保留)
export const GITHUB_REPO_URL: string = MOCK_DATA.urls.github
export const HELP_URL: string = MOCK_DATA.urls.help
