// GENERATED by scripts/port-demo-mockdata.mjs — 勿手改;源:docs/demo/js/data.js @ 06ff9ba
// mock 数据单一事实来源;组件禁止直接 import,须经 data/ 接缝(src/renderer/src/data/index.ts)

import type { AppUrls } from '@shared/models'

// 仅剩静态链接(demo 其余 mock 数据已随各阶段真实化逐一剔除,见各 delete 行注释)
export interface MockData {
  urls: AppUrls
}

export const MOCK_DATA: MockData = {
  "urls": {
    "github": "https://github.com/BeCrafter/Launcher",
    "help": "https://github.com/BeCrafter/Launcher/blob/main/Help.md"
  }
}

// demo data.js 末尾的 URL 别名(原样保留)
export const GITHUB_REPO_URL: string = MOCK_DATA.urls.github
export const HELP_URL: string = MOCK_DATA.urls.help
